### ISSUE TITLE
Inline match rule feature suggestion

### ISSUE THREAD

**Issue by eliabexp** [UziTech/marked-katex-extension#314] opened 2024-01-01 22:03 UTC
I have a suggestion to add the support of inline katex inside parentheses, this would be very useful to refer to math formulas in a content

Here are some examples:

`($a_1$)` and `($r$)`:

![image](https://github.com/UziTech/marked-katex-extension/assets/74092305/01b3b2cd-257f-4557-bd61-cefe0fa8b3bd)

`($r$)`:

![image](https://github.com/UziTech/marked-katex-extension/assets/74092305/ceddb51a-fcf4-489e-ad2f-70528cc89a3f)

**Comment by UziTech** [comment] 2024-01-02 01:44
`( $a_1$ )` and `( $r$ )` should work. Is there a reason you can't add a space between the parentheses and katex?

**Comment by eliabexp** [comment] 2024-01-02 02:08
I gave the parentheses example but there are some other cases that this isn't feasible, like when the expression is after `\n`, it appears awkward to include spaces at the line start

**Comment by UziTech** [comment] 2024-01-02 02:10
You don't need a space after a new line. You need any space character which includes a new line.

**Comment by eliabexp** [comment] 2024-01-02 02:36
I mean in this example case

```js
import { marked, use } from 'marked'
import markedKatex from 'marked-katex-extension'

use(markedKatex({ output: 'mathml' }))

const text = marked("$a_n=$ General Term\n$a_1=$ First Term\n$n=$ Term position\n$r=$ Common difference")

console.log(text) // just the first line katex is rendered correctly
```

**Comment by UziTech** [comment] 2024-01-02 05:53
If those terms are not supposed to be inline then there should be two newlines between then. If they are supposed to be inline than you should write them inline with a space or have a space at the beginning of the line to indicate that they should appear inline.

It looks like it does need to be a space character. We could allow a newline char before inline but I think that might allow more badly formatted markdown.

**Comment by UziTech** [comment] 2024-01-02 05:56
The parentheses we can't allow without spaces because we would need a way to check for nested parentheses inside the katex. And it is just much easier to put spaces in.

**Comment by eliabexp** [comment] 2024-01-05 15:43
but in this case the markdown would be bad formatted, imagine having to add spaces from the second term forward and not in the first

```
$katex1$ String
 $katex2$ String
 $katex3$ String
 $katex4$ String
 ```

**Comment by UziTech** [comment] 2024-01-06 00:56
I think we want to encourage a blank line between lines by making users make it look worse if they want to have markdown that is badly formatted.

**Comment by eliabexp** [comment] 2024-01-06 01:22
I think the parser is failing to perform the required matching of terms, what makes the markdown content weird considering that space rule

This is a pratical example:

![image](https://github.com/UziTech/marked-katex-extension/assets/74092305/7c7a03ab-61cc-4463-b261-65ffa65d6065)

I don't think I am formatting the markdown incorrectly when attempting to do this.

**Comment by UziTech** [comment] 2024-01-06 01:55
What is the markdown for that example?

**Comment by UziTech** [comment] 2024-01-06 02:26
It looks like this markdown would work to create that output:

```md
$
S_n = \\frac{(a_1 + a_n) * n}{2}
$

Where:

$
S_n = \\text{Sum of terms}\\newline
a_1 = \\text{First Term}\\newline
a_n = \\text{Last term}\\newline
n = \\text{Term amount}
$
```

Those boxes would each need to be single katex. It wouldn't work the way you want even if we allowed new line before inline katex.

**Comment by eliabexp** [comment] 2024-01-06 02:31
```
```formula\n$S_n=\\frac{\\left(a_1+a_{n}\\right)\\cdot n}{2}$\n```\nWhere:\n```formula\n$S_n=$ Sum of terms\n $a_1=$ First term\n $a_n=$ Last term\n$n=$ Term amount\n```
```

another point to note is these rules seems overly restricted, considering that the *emphasis* and other simmilar inline notations doesn't have this rule of putting spaces inside the parentheses like we can see (*here*)

**Comment by eliabexp** [comment] 2024-01-06 02:37
> It looks like this markdown would work to create that output:
> 
> ```
> $
> S_n = \\frac{(a_1 + a_n) * n}{2}
> $
> 
> Where:
> 
> $
> S_n = \\text{Sum of terms}\\newline
> a_1 = \\text{First Term}\\newline
> a_n = \\text{Last term}\\newline
> n = \\text{Term amount}
> $
> ```
> 
> Those boxes would each need to be single katex. It wouldn't work the way you want even if we allowed new line before inline katex.

I tried it but I had some problems displaying some letters with accent like ã and á in `\\text` in the browser, and my application works with languages that uses this characters

**Comment by UziTech** [comment] 2024-01-06 02:44
> another point to note is these rules seems overly restricted, considering that the emphasis and other simmilar inline notations doesn't have this rule of putting spaces inside the parentheses like we can see (*here*)

Ya and do you know how much code it takes to be able to do that? *a lot*

Not worth it for this small extension when adding spaces is so easy.

If you want to make a more robust katex extension go right ahead. You can take all the code from this repo and add whatever features you want to it.

**Comment by UziTech** [comment] 2024-01-06 03:04
>```
>```formula\n$S_n=\\frac{\\left(a_1+a_{n}\\right)\\cdot n}{2}$\n```\nWhere:\n```formula\n$S_n=$ Sum of terms\n $a_1=$ First term\n $a_n=$ Last term\n $n=$ Term amount\n```
>```

That markdown won't work either since the katex is in a code block and it would not convert the katex with this extension.

**Comment by UziTech** [comment] 2024-01-06 03:06
It looks like

```
$katex1$ String
$katex2$ String
$katex3$ String
$katex4$ String
```

Does work with the `breaks: true` option for marked

**Comment by eliabexp** [comment] 2024-01-07 02:25
> It looks like
> 
> ```
> $katex1$ String
> $katex2$ String
> $katex3$ String
> $katex4$ String
> ```
> 
> Does work with the `breaks: true` option for marked

It worked! Ty so much

**Comment by UziTech** [comment] 2024-01-07 02:54
Going to close this since it is working as intended

**Closed by UziTech** 2024-01-07 02:54 UTC
